name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # state management
  flutter_bloc: ^8.1.2
  # comparing objects
  equatable: ^2.0.5
  # service locator
  get_it: ^7.6.0
  # date format
  intl: ^0.18.1
  # database
  floor: ^1.4.2
  # make request to API
  retrofit: ^4.4.2
  # hooks
  flutter_hooks: ^0.18.3
  # cached image
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  floor_generator: ^1.5.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
